### ISSUE TITLE
run success but not output file 

### ISSUE THREAD

**Issue by quyho0944** [ctlab/metacherchant#15]
hello, when i try to run you tools with my data
```
 metacherchant.sh --tool environment-finder --k 31 --coverage=5 --reads ../test_100k_cm_1.fastq --seq ../../mgs2amr/dataAndScripts/ARG.fasta --maxradius 2000 --output ./cm_metachechant/ --work-dir ./cm_metachechant/metacherchant_logs --maxkmers=100000 --bothdirs=False --chunklength=250 
 ```
 anything was fine, i did't see any error. but when i check my output folder nothing inside.
 i give you my log file, if you see any thing wrong please let me know, this tool is import to run my pipeline
[log_txt.txt](https://github.com/ctlab/metacherchant/files/15250852/log_txt.txt)
.

**Comment by ivartb** [comment]
Hello!

The log file indicates that none of the ARG sequences were found in the input fastq file ("Could not find any k-mers of the target gene in the input").

This can be caused by the combination of small number of reads and large value of `--coverage=5`. Could you please try to set `--coverage=0` or send me `test_100k_cm_1.fastq` and `mgs2amr/dataAndScripts/ARG.fasta` files for further evaluation.

Kind regards,
Artem

**Comment by quyho0944** [comment]
thank you so much, it work.
